spring:
  application:
    name: ProductCatalogService

  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: springuser
    password: dev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true